config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :"teacher"
  resources :"student"
  resources :"admin"
  resources :"attendence"

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendence.rb
class Attendence < ApplicationRecord

    belongs_to :student
    belongs_to :teacher

end

app/models/blood.rb
class Blood < ApplicationRecord
end

app/models/standard.rb
class Standard < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord

    has_many :attendences
    has_many :students, :through => :attendences

    before_save :set_classteacher
    before_update :set_mark
    before_update :set_average  
    before_update :set_grade

    private

    def set_mark
        unless mark1.nil? && mark2.nil? && mark3.nil? && mark4.nil? && mark5.nil?
            self[:total] = mark1 + mark2 + mark3 + mark4 + mark5
        end
    end

    def set_average
        unless mark1.nil? && mark2.nil? && mark3.nil? && mark4.nil? && mark5.nil?
            self[:average] = (mark1 + mark2 + mark3 + mark4 + mark5)/5
        end
    end

    def set_grade
        unless mark1.nil? && mark2.nil? && mark3.nil? && mark4.nil? && mark5.nil?
        avg = (mark1 + mark2 + mark3 + mark4 + mark5)/5
        val = true
        if mark1<35 || mark2<35 || mark3<35 || mark4<35 ||mark5<35
            val = false
        end

        if avg>=90 && val
            self[:grade] = "A"
        elsif avg>=80 && avg<90 && val
            self[:grade] = "B"
        elsif avg>=70 && avg<80 && val
            self[:grade] = "C"
        elsif avg>=35 && avg<70 && val
            self[:grade] = "D"
        else
            self[:grade] = "F"

        end
        end
    end

    def set_classteacher
        @classteacher = Teacher.find_by(:classroom => classroom)
        self[:teachername] = @classteacher.name
    end

end

app/models/teacher.rb
class Teacher < ApplicationRecord

    has_many :attendences
    has_many :students, :through => :attendences
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendence_controller.rb
class AttendenceController < ApplicationController

    def index
    end

    def new
        @attendence = Attendence.new()
    end

    def create
        @teacher = Teacher.find(1)
        
        params[:attendence][:student_id].each do |id|
            if !id.empty?
                @teacher.attendences.build(:student_id => id)
            end
        end
    end

    private

    def attendence_params
        params.require(:attendence).permit(:teacher_id, :student_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/student_controller.rb
class StudentController < ApplicationController


    def index
        @student = Student.all
    end

    def show
        @student = Student.find(params[:id])
    end

    def new
        @student = Student.new()
    end

    def create
        @student = Student.new(student_params)
        if @student.save()
            redirect_to action: "index", :notice => "student data saved succesfully" 
        end
    end

    def edit
        @student = Student.find(params[:id])
    end

    def update

        @student = Student.find(params[:id])
        if @student.update(student_params)
            redirect_to action: "index", :notice => "student data saved succesfully"
        end 
    end

    def destroy
        @student = Student.find(params[:id])
        @student.destroy
        redirect_to action: "index", notice => "student data deleted succesfully" 
    end

    private

    def student_params
        params.require(:student).permit(:rollno, :name, :classroom, :bloodgroup, :usertype, :mark1, :mark2, :mark3, :mark4, :mark5, :total, :average, :grade, :teachername)
    end

    
end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController


    def index
        @teacher = Teacher.all
    end

    def show
        @teacher = Teacher.find(params[:id])
    end

    def new
        @teacher = Teacher.new()
    end

    def create
        @teacher = Teacher.new(student_params)
        if @teacher.save()
            redirect_to action: "index", :notice => "Teacher data saved succesfully" 
        end
    end

    def edit
        @teacher = Teacher.find(params[:id])
    end

    def update

        @teacher = Teacher.find(params[:id])
        if @teacher.update(student_params)
            redirect_to action: "index", :notice => "Teacher data saved succesfully"
        end 
    end

    def destroy
        @teacher = Teacher.find(params[:id])
        @teacher.destroy
        redirect_to action: "index", notice => "Teacher data deleted succesfully" 
    end

    private

    def student_params
        params.require(:teacher).permit(:empid, :name, :classroom, :bloodgroup, :usertype)
    end

    
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendence_helper.rb
module AttendenceHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/admin/_adminheader.html.erb
<header>
	<div class="left_area">
		<h3><span>School</span>management</h3>
	</div>
	<div class="right_area">
		<a href="" class="logout_btn">Logout</a>
	</div>
</header>
<div class="sidebar">
	<center>
		<img src="" class="profile_image" alt=""/>
		<h4>Admin</
		h4>
	</center>
	<%= link_to "Home", :controller => "admin", :action => "index" %>
	<%= link_to "Students Details", :controller => "student", :action => "index" %>
	<%= link_to "Teachers Details", :controller => "teacher", :action => "index" %>
	<%= link_to "Attendence", :controller => "attendence", :action => "index" %>
</div>

app/views/admin/index.html.erb
<%= render "adminheader" %>
<div class="container" style="width:60%; position:relative; top:100px; z-index:0;">
<h1 style="position:relative; top:50px; ">Welcome Administrator</h1>
</div>

app/views/attendence/index.html.erb
<%= render "admin/adminheader" %>
<div class="container" style="width:60%; position:relative; top:100px; z-index:0;">
<h1 style="position:relative; top:50px; ">Attendence Register</h1>
<br/><br/><br/>
<%= link_to "Put attendence", new_attendence_path, class:"btn btn-primary" %>
</div>

app/views/attendence/new.html.erb
<%= render "admin/adminheader" %>
<div class="container" style="width:60%; position:relative; top:100px; z-index:0;">
<br/>
<h3><b>Student Information<b></h3>
<br/>
<%= form_for @attendence, url: "/attendence", method: "POST" do |d| %>
    <div class="form-group">
    <%= d.label :Teacher %>
    <%= d.select :teacher_id, Teacher.all.map{ |teach| [teach.name, teach.id ]}, include_blank: true %>
    </div><br/>

    <div class="form-group">
    <%= d.label :students %>
    <%= collection_select(:attendence, :student_id, Student.all, :id, :name, {}, {:multiple => true} ) %>
    </div><br/>

    <button type="submit" class="btn btn-primary">Submit</button> 
<% end %>   
</div>

app/views/home/index.html.erb
<h1>Shivan</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/student/edit.html.erb
<%= render "admin/adminheader" %>
<div class="container" style="width:60%; position:relative; top:100px;">
<br/>
<h3><b>Student Information<b></h3>
<br/>
<%= form_for @student, url: "/student/#{@student.id}", method: "PUT" do |d| %>

    <div class="form-group">
      <%= d.label :RollNo %>
      <%= d.text_field :rollno, class:"form-control", placeholder:"Enter the RollNo" %>
    </div><br/>

    <div class="form-group">
    <%= d.label :Name %>
    <%= d.text_field :name, class:"form-control", placeholder:"Enter the Name" %>
    </div><br/>

  <div class="form-group">
  <%= d.label :Standard %>
  <%= d.select :classroom, Standard.all.map{ |std| [std.classroom, std.classroom ]}, include_blank: true %>
  </div><br/>

  <div class="form-group">
  <%= d.label :Bloodgroup %>
  <%= d.select :bloodgroup, Blood.all.map{ |b| [b.bloodname, b.bloodname]}, include_blank: true %>
  </div><br/>

  <div class="form-group">
  <%= d.label :Usertype %>
  <%= d.select(:usertype, options_for_select([["STUDENT", "STUDENT"], ["TEACHER", "TEACHER"]]), include_blank: true) %>
  </div><br/>

  <div class="form-group">
    <%= d.label :Classteacher %>
    <%= d.text_field :teachername, class:"form-control", placeholder:"Enter the Name" %>
    </div><br/>

  <div class="form-group">
  <%= d.label :Tamil%>
  <%= d.text_field :mark1, class:"form-control", placeholder:"Enter the mark" %>
  </div><br/>

  <div class="form-group">
  <%= d.label :English %>
  <%= d.text_field :mark2, class:"form-control", placeholder:"Enter the mark" %>
  </div><br/>

  <div class="form-group">
  <%= d.label :Maths %>
  <%= d.text_field :mark3, class:"form-control", placeholder:"Enter the mark" %>
  </div><br/>

  <div class="form-group">
  <%= d.label :Science %>
  <%= d.text_field :mark4, class:"form-control", placeholder:"Enter the mark" %>
  </div><br/>

  <div class="form-group">
  <%= d.label :Social %>
  <%= d.text_field :mark5, class:"form-control", placeholder:"Enter the mark" %>
  </div><br/>

  <button type="submit" class="btn btn-primary">Submit</button>
  <% end %>
</div>

app/views/student/index.html.erb
<%= render "admin/adminheader" %>
<div class="container" style="width:60%; position:relative; top:100px;">
<br/>


<h3><b>Students Table</b></h3>
<br/>
<div class="container-fluid">
<table class="table table-hover">
  <thead class="thead-dark table-info">
    <tr>
      <th scope="col">RollNo</th>
      <th scope="col">Name</th>
      <th scope="col">Class</th>
      <th scope="col">BloodGroup</th>
      <th scope="col">ClassTeacher</th>
      <th scope="col">Mark</th>
      <th scope="col">Average</th>  
      <th scope="col">Grade</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @student.each do |student| %>
    <tr>
        <td><%= student.rollno %></td>
      <td><%= student.name %></td>
      <td><%= student.classroom %></td>
      <td><%= student.bloodgroup %></td>
      <td><%= student.teachername %></td>
      <td><%= student.total %></td>
      <td><%= student.average %></td>
      <td><%= student.grade %></td>
      <td><%= link_to "Show", controller:"student", action:"show", id:student.id %></td>
      <td><%= link_to "Edit", controller:"student", action:"edit", id:student.id %></td>
      <td><%= link_to "Delete", student_path(student.id), :method => :delete, :data => {:confirm => "Are you sure to delete #{student.name} Details "}  %></td>
      </tr>
<% end %>
  </tbody>
</table>
<br/>
<%= link_to "Create student", new_student_path, class:"btn btn-primary" %>
</div>
</div>

app/views/student/new.html.erb
<%= render "admin/adminheader" %>
<div class="container" style="width:60%; position:relative; top:100px; z-index:1;">
<br/>
<h3><b>Student Information<b></h3>
<br/>
<%= form_for @student, url: "/student", method: "POST" do |d| %>

    <div class="form-group">
      <%= d.label :RollNo %>
      <%= d.text_field :rollno, class:"form-control", placeholder:"Enter the RollNo" %>
    </div><br/>

    <div class="form-group">
    <%= d.label :Name %>
    <%= d.text_field :name, class:"form-control", placeholder:"Enter the Name" %>
    </div><br/>

  <div class="form-group">
  <%= d.label :Standard %>
  <%= d.select :classroom, Standard.all.map{ |std| [std.classroom, std.classroom ]}, include_blank: true %>
  </div><br/>

  <div class="form-group">
  <%= d.label :Bloodgroup %>
  <%= d.select :bloodgroup, Blood.all.map{ |b| [b.bloodname, b.bloodname]}, include_blank: true %>
  </div><br/>

  <div class="form-group">
  <%= d.label :Usertype %>
  <%= d.select(:usertype, options_for_select([["STUDENT", "STUDENT"], ["TEACHER", "TEACHER"]]), include_blank: true) %>
  </div><br/>

  <button type="submit" class="btn btn-primary">Submit</button>
  <% end %>
</div>

app/views/student/show.html.erb
<%= render "admin/adminheader" %>

<div class="container" style="width:60%; position:relative; top:100px;">
<br/>

<label><h2><b>Student Name : </b></h2></label>
<b class="fs-3 ml-auto"><%= @student.name %></b> </br>
<br/>
<div class="container-fluid">
<table class="table table-hover">
  <thead class="thead-dark table-info">
    <tr>
      <th scope="col">Subject</th>
      <th scope="col">Mark</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td><b>Tamil</b></td>
         <td><%= @student.mark1 %></td>
      </tr>
      <tr>
        <td><b>English</b></td>
         <td><%= @student.mark2 %></td>
      </tr>
      <tr>
        <td><b>Maths</b></td>
         <td><%= @student.mark3 %></td>
      </tr>
      <tr>
        <td><b>Science</b></td>
         <td><%= @student.mark4 %></td>
      </tr>
      <tr>
        <td><b>Social</b></td>
         <td><%= @student.mark5 %></td>
      </tr>
      <tr class="thead-dark table-info" >
        <td><b>Total</b></td>
         <td><%= @student.total %></td>
      </tr>
      <tr class="thead-dark table-info" >
      <td><b>Grade</b></td>
       <td><%= @student.grade %></td>
    </tr>
  </tbody>
</table>
<br/>
<center class="fs-4" ><b>GRADE- A : Very Good  / GRADE- B : Good  / GRADE- C : Average  / GRADE- F : Fail</b></center>  
<br/>
<%= link_to "Back", :controller => "student", :action => "index", class:"btn btn-primary" %>
</div>
</div>

app/views/teacher/edit.html.erb
<%= render "admin/adminheader" %>
<div class="container" style="width:60%; position:relative; top:100px; z-index:1;">
<br/>
<h3><b>Teacher Information<b></h3>
<br/>
<%= form_for @teacher, url: "/teacher/#{@teacher.id}", method: "PUT" do |d| %>

    <div class="form-group">
      <%= d.label :EmpId %>
      <%= d.text_field :empid, class:"form-control", placeholder:"Enter the EmpId" %>
    </div><br/>

    <div class="form-group">
    <%= d.label :Name %>
    <%= d.text_field :name, class:"form-control", placeholder:"Enter the Name" %>
    </div><br/>

  <div class="form-group">
  <%= d.label :Class %>
  <%= d.select :classroom, Standard.all.map{ |std| [std.classroom, std.classroom ]}, include_blank: true %>
  </div><br/>

  <div class="form-group">
  <%= d.label :Bloodgroup %>
  <%= d.select :bloodgroup, Blood.all.map{ |b| [b.bloodname, b.bloodname]}, include_blank: true %>
  </div><br/>

  <div class="form-group">
  <%= d.label :Usertype %>
  <%= d.select(:usertype, options_for_select([["STUDENT", "STUDENT"], ["TEACHER", "TEACHER"]]), include_blank: true) %>
  </div><br/>

  <button type="submit" class="btn btn-primary">Submit</button>
  <% end %>
</div>

app/views/teacher/index.html.erb
<%= render "admin/adminheader" %>
<div class="container" style="width:60%; position:relative; top:100px;">
<br/>


<h3><b>Teachers Details</b></h3>
<br/>
<div class="container-fluid">
<table class="table table-hover">
  <thead class="thead-dark table-info">
    <tr>
      <th scope="col">EmpId</th>
      <th scope="col">Name</th>
      <th scope="col">Class</th>
      <th scope="col">BloodGroup</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @teacher.each do |teacher| %>
    <tr>
        <td><%= teacher.empid %></td>
      <td><%= teacher.name %></td>
      <td><%= teacher.classroom %></td>
      <td><%= teacher.bloodgroup %></td>
      <td><%= link_to "Show", controller:"teacher", action:"show", id:teacher.id %></td>
      <td><%= link_to "Edit", controller:"teacher", action:"edit", id:teacher.id %></td>
      <td><%= link_to "Delete", teacher_path(teacher.id), :method => :delete, :data => {:confirm => "Are you sure to delete #{teacher.name} Details "}  %></td>
      </tr>
<% end %>
  </tbody>
</table>
<br/>
<%= link_to "Create Teacher", new_teacher_path, class:"btn btn-primary" %>
</div>
</div>

app/views/teacher/new.html.erb
<%= render "admin/adminheader" %>
<div class="container" style="width:60%; position:relative; top:100px; z-index:1;">
<br/>
<h3><b>Teacher Information<b></h3>
<br/>
<%= form_for @teacher, url: "/teacher", method: "POST" do |d| %>

    <div class="form-group">
      <%= d.label :EmpId %>
      <%= d.text_field :empid, class:"form-control", placeholder:"Enter the EmpId" %>
    </div><br/>

    <div class="form-group">
    <%= d.label :Name %>
    <%= d.text_field :name, class:"form-control", placeholder:"Enter the Name" %>
    </div><br/>

  <div class="form-group">
  <%= d.label :Class %>
  <%= d.select :classroom, Standard.all.map{ |std| [std.classroom, std.classroom ]}, include_blank: true %>
  </div><br/>

  <div class="form-group">
  <%= d.label :Bloodgroup %>
  <%= d.select :bloodgroup, Blood.all.map{ |b| [b.bloodname, b.bloodname]}, include_blank: true %>
  </div><br/>

  <div class="form-group">
  <%= d.label :Usertype %>
  <%= d.select(:usertype, options_for_select([["STUDENT", "STUDENT"], ["TEACHER", "TEACHER"]]), include_blank: true) %>
  </div><br/>

  <button type="submit" class="btn btn-primary">Submit</button>
  <% end %>
</div>

app/views/teacher/show.html.erb
<%= render "admin/adminheader" %>

<div class="container" style="width:60%; position:relative; top:100px;">
<br/>

<label><h2><b>Teacher Name : </b></h2></label>
<b class="fs-3 ml-auto"><%= @teacher.name %></b> </br>
<br/>

<%= link_to "Back", :controller => "teacher", :action => "index", class:"btn btn-primary" %>
</div>